name: tool
publish_to: none
dependencies:
  charcode: ^1.1.3
  glob: ^1.2.0
  markdown: ^2.1.3
  mime_type: ^0.3.0
  mustache_template: ^1.0.0
  path: ^1.7.0
  sass: ^1.26.5
  shelf: ^0.7.5
  string_scanner: ^1.0.5
